## Count clusters in a 2-D array.
In the input array, a cluster is a group of more than one `1` connected with each other in "up", "down", "right" or "left" directions.  Diagonal neighbours are not considered in the same cluster.

In [1]:
import numpy as np
import numpy.random as rnd
import sys
sys.version_info

sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

In [2]:
def findCluster(inp):
    nr = len(inp)
    nc = len(inp[0])
    lst = list()
    visit = [[False for _ in range(nc)] for _ in range(nr)]
    
    def work(i, j):
        if visit[i][j]:
#             breakpoint()
            return 0
        visit[i][j] = True
        res = 0
        if inp[i][j] == 1:
            a, b, c, d = 0, 0, 0, 0
            if i - 1 >= 0:
                a = work(i - 1, j)
            if i + 1 < nr:
                b = work(i + 1, j)
            if j - 1 >= 0:
                c = work(i, j - 1)
            if j + 1 < nc:
                d = work(i, j + 1)
            res = 1 + a + b + c + d
        return res
    
    
    n_clu = 0
    for i in range(nr):
        for j in range(nc):
            if work(i, j) > 1:
                n_clu += 1
    return n_clu

In [3]:
c = 6
r = 8
l1 = [[rnd.randint(0, 2) for _ in range(c)] for _ in range(r)]
print(np.array(l1))

findCluster(l1)

[[1 0 0 0 1 0]
 [1 1 0 0 1 0]
 [0 1 1 0 0 0]
 [1 1 0 0 0 0]
 [0 1 1 1 0 0]
 [0 0 0 1 1 1]
 [1 1 0 1 1 1]
 [0 1 0 1 1 0]]


3